### ISSUE TITLE
💰 300 USDT Bounty - "OHLC charts for USD/RAM & EOS/RAM prices"

### ISSUE THREAD

**Issue by PomeloBounties** [pomelo-io/Bounties#30]
## Bounty
**OHLC charts for USD/RAM & EOS/RAM prices** created by @DenisCarriere on [Pomelo Bounties](https://bounties.pomelo.io)

## Summary
*## Scope

- [ ] OHLC charts
  - [ ] Open
  - [ ] High
  - [ ] Low
  - [ ] Close
- [ ] Candle Symbol
  - [ ] Red: Bearish
  - [ ] Green: Bullish
- [ ] RAM prices:
  - [ ] EOS/RAM prices
  - [ ] EOS/USD prices
- [ ] must include 24h daily candles
  - [ ] (optional) smaller timeframe (5m, 15m, 30m, 1h, 4h, 1d, 1w, 1m)
- [ ] must have historical data from at least `2023-11`
  - [ ] (optional) have historical data since (2019)
  - [ ] (optional) have historical data since genesis (2018)

## Available bounty applicants
- Existing platforms that offer RAM/EOS price charts
  - https://defibox.io/ram/
  - https://eoseyes.com/ram
  - https://newdex.io/resources/ram

## References
- https://datavizcatalogue.com/methods/OHLC_chart.html*

## Apply
[https://bounties.pomelo.io/4ef2fc4d4e4f](https://bounties.pomelo.io/4ef2fc4d4e4f)

## Original Issue
[https://github.com/pomelo-io/Bounties/issues/29](https://github.com/pomelo-io/Bounties/issues/29)

## Title
OHLC charts for USD/RAM & EOS/RAM prices

## Scope

- [ ] OHLC charts
  - [ ] Open
  - [ ] High
  - [ ] Low
  - [ ] Close
- [ ] Candle Symbol
  - [ ] Red: Bearish
  - [ ] Green: Bullish
- [ ] RAM prices:
  - [ ] EOS/RAM prices
  - [ ] EOS/USD prices
- [ ] must include 24h daily candles
  - [ ] (optional) smaller timeframe (5m, 15m, 30m, 1h, 4h, 1d, 1w, 1m)
- [ ] must have historical data from at least `2023-11`
  - [ ] (optional) have historical data since (2019)
  - [ ] (optional) have historical data since genesis (2018)

## Available bounty applicants
- Existing platforms that offer RAM/EOS price charts
  - https://defibox.io/ram/
  - https://eoseyes.com/ram
  - https://newdex.io/resources/ram

## References
- https://datavizcatalogue.com/methods/OHLC_chart.html

<img width="814" alt="image" src="https://github.com/pomelo-io/Bounties/assets/550895/e2baf61b-275f-4b90-9fa2-26b37c5e67ee">

<img width="363" alt="image" src="https://github.com/pomelo-io/Bounties/assets/550895/fb634b27-4802-4f1e-93fd-4c09190ef204">

## Base Reward
**300.0000 USDT**

## Note
For technical discussion use the original issue. This issue is for tracking the bounty application and implementation progress.

**Comment by PomeloBounties** [comment]
Bounty fully [funded](https://bloks.io/transaction/e5e9f30372c15c548b80b9551a4393e78c07784bc5b4522c2092d5ce2efd4f15) with **300.0000 USDT** reward!

Accepting applications [here](https://bounties.pomelo.io/4ef2fc4d4e4f)

**Comment by PomeloBounties** [comment]
Bounty application submitted by @bbtheraidg with a message:
 > Hello, are you still in search of a data analyst for ohlc charts regarding USD or EOS to ram? I can offer statistics if needed, I’m inquiring for more details and more specifics. Thanks

Waiting for your approval @DenisCarriere

**Comment by DenisCarriere** [comment]
@bbtheraidg thanks for inquiring, as for this requirement, it would require an existing platform to support OHLC charts of RAM/USD prices

As for offering statistics, that would be a different scope of work, which I can open another bounty for a data retrieval task https://github.com/eosnetworkfoundation/eosio.wram/issues/2

**Comment by PomeloBounties** [comment]
Bounty application denied for @bbtheraidg with a message:
 > See message here:
> 
> https://github.com/pomelo-io/Bounties/issues/30#issuecomment-2002605680

**Comment by PomeloBounties** [comment]
Bounty application submitted by @Reppooo with a message:
 > .

Waiting for your approval @DenisCarriere

**Comment by PomeloBounties** [comment]
Bounty application submitted by @Reppooo with a message:
 > Not fund

Waiting for your approval @DenisCarriere

**Comment by PomeloBounties** [comment]
Bounty application denied for @Reppooo with a message:
 > no details

**Comment by PomeloBounties** [comment]
Bounty application submitted by @tofan428 with a message:
 > N/A

Waiting for your approval @DenisCarriere

**Comment by PomeloBounties** [comment]
Bounty application denied for @tofan428 with a message:
 > N/A

**Comment by PomeloBounties** [comment]
Bounty application submitted by @defiob with a message:
 > All historical data has been crawled and the K-line data of 1h, 1d, 1w and 1m has been shown

Waiting for your approval @DenisCarriere

**Comment by PomeloBounties** [comment]
Bounty application approved. Good luck @defiob!

**Comment by PomeloBounties** [comment]
Bounty funds released and ready to be claimed @defiob!

**Comment by PomeloBounties** [comment]
Bounty **300.0000 USDT** successfully [claimed](https://bloks.io/transaction/a83f79d314b97f458dcd9810bdb9a6329f061fe1b2abeb26dfc3c3a18239aee4)
