### ISSUE TITLE
💰 5 USDT Bounty - "Test Pomelo Bounties"

### ISSUE THREAD

**Issue by PomeloBounties** [pomelo-io/Bounties#6]
## Bounty
**Test Pomelo Bounties** created by @betatester69 on [Pomelo Bounties](https://bounties.pomelo.io)

## Summary
*Write a Test Bounty and Submit Work for it on the Pomelo Platform.*

## Apply
[https://bounties.pomelo.io/3dbf3af4fbdc](https://bounties.pomelo.io/3dbf3af4fbdc)

## Original Issue
[https://github.com/betatester69/test/issues/1](https://github.com/betatester69/test/issues/1)

## Title
Test Pomelo Bounties

## Body
Test the Pomelo bounties platform by creating a bounty and then submitting work for that bounty

## Base Reward
**5.0000 USDT**

## Note
For technical discussion use the original issue. This issue is for tracking the bounty application and implementation progress.

**Comment by PomeloBounties** [comment]
Bounty fully [funded](https://bloks.io/transaction/06cffba5c443d403eed982c22544b523da3884d2fe440753a49a93c5869bd837) with **5.0000 USDT** reward!

Accepting applications [here](https://bounties.pomelo.io/3dbf3af4fbdc)

**Comment by PomeloBounties** [comment]
Bounty application submitted by @Mahhheshh with a message:
 > https://github.com/Mahhheshh/LenDen/issues/3

Waiting for your approval @betatester69

**Comment by PomeloBounties** [comment]
Bounty application submitted by @Erithon with a message:
 > Top

Waiting for your approval @betatester69

**Comment by PomeloBounties** [comment]
Bounty application submitted by @Lucianoelpitudo with a message:
 > Yo quiero hacerlo

Waiting for your approval @betatester69

**Comment by PomeloBounties** [comment]
Bounty application submitted by @Kak-Nan with a message:
 > Pomelo bounty starter

Waiting for your approval @betatester69

**Comment by PomeloBounties** [comment]
Bounty application submitted by @Kak-Nan with a message:
 > Prizes are received in the form of digital currency

Waiting for your approval @betatester69

**Comment by PomeloBounties** [comment]
Bounty application submitted by @r41h0rn with a message:
 > :)

Waiting for your approval @betatester69

**Comment by r41h0rn** [comment]
ok

**Comment by PomeloBounties** [comment]
Bounty application submitted by @Dublin7 with a message:
 > N/A

Waiting for your approval @betatester69

**Comment by PomeloBounties** [comment]
Bounty application submitted by @sulimblora with a message:
 > I think good project

Waiting for your approval @betatester69

**Comment by PomeloBounties** [comment]
Bounty application submitted by @pomelo-infundr with a message:
 > Test)

Waiting for your approval @betatester69

**Comment by PomeloBounties** [comment]
Bounty application submitted by @r41h0rn with a message:
 > N/A

Waiting for your approval @betatester69

**Comment by PomeloBounties** [comment]
Bounty application submitted by @Ludmila0502 with a message:
 > Pomelo bounty tested with all requirements...

Waiting for your approval @betatester69

**Comment by PomeloBounties** [comment]
Bounty application submitted by @huyvip18xx with a message:
 > good

Waiting for your approval @betatester69

**Comment by PomeloBounties** [comment]
Bounty application submitted by @Adi12113 with a message:
 > about 1 month ago
> 
> Bounty fully funded with 5 USDT reward!
> 
> Accepting applications here

Waiting for your approval @betatester69

**Comment by PomeloBounties** [comment]
Bounty application submitted by @Adi12113 with a message:
 > about 1 month ago
> 
> Bounty fully funded with 17.0000 USDT reward!
> 
> Accepting applications here

Waiting for your approval @betatester69

**Comment by Lucianoelpitudo** [comment]
> ## Generosidad
> **Prueba las recompensas de pomelo** creadas por@betatester69en [recompensas de pomelo](https://bounties.pomelo.io)
> 
> ## Resumen
> _Escriba una recompensa de prueba y envíe el trabajo en la plataforma Pomelo._
> 
> ## Aplicar
> https://bounties.pomelo.io/3dbf3af4fbdc
> 
> ## Edición original
> [betatester69/prueba#1](https://github.com/betatester69/test/issues/1)
> 
> ## Título
> Pruebe las recompensas de pomelo
> 
> ## Cuerpo
> Pruebe la plataforma de recompensas de Pomelo creando una recompensa y luego enviando trabajo para esa recompensa
> 
> ## Recompensa básica
> **5.0000 USDT**
> 
> ## Nota
> Para discusiones técnicas utilice el número original. Este problema es para rastrear la solicitud de recompensa y el progreso de su implementación.

Y?

**Comment by PomeloBounties** [comment]
Bounty application approved. Good luck @Mahhheshh!

**Comment by PomeloBounties** [comment]
Bounty funds released and ready to be claimed @Mahhheshh!

**Comment by Mahhheshh** [comment]
How do i claim??

**Comment by PomeloBounties** [comment]
Bounty **5.0000 USDT** successfully [claimed](https://bloks.io/transaction/4aa49f3cb8c3f1c0dd4fc2df0676283c6ac7ae583a122b5c70415e883cd2c501)
