### ISSUE TITLE
💰 45 USDT Bounty - "Create Project Submission Form"

### ISSUE THREAD

**Issue by PomeloBounties** [pomelo-io/Bounties#8]
## Bounty
**Create Project Submission Form** created by @andrewrec on [Pomelo Bounties](https://bounties.pomelo.io)

## Summary
*Develop Project Submission Form

The task at hand is to develop a project submission form for the music map, which is a user-curated platform for displaying music projects. The form should allow Polaris users to submit projects, such as albums, in a standard format with all necessary information. The form should also have the ability to add more entries to certain fields and generate additional questions based on the answers to some fields.

Optionally, the form should be able to fetch data from Discogs or another music metadata database. Upon submission, the form should package the data into a transaction that can be sent to the blockchain.

The deliverables for this task include designing the project/release submission form. The form should have fields for data source, project name, release date, record label, liner notes, bio, artwork, multimedia, project groups, artists, technicians, and tracks. The form should also have the ability to add multiple entries for certain fields.*

## Apply
[https://bounties.pomelo.io/14e2144db1bc](https://bounties.pomelo.io/14e2144db1bc)

## Original Issue
[https://github.com/UrsaPolarisRecords/Polaris/issues/15](https://github.com/UrsaPolarisRecords/Polaris/issues/15)

## Title
Create Project Submission Form

#### User Story
 As a _**Polaris User**_, I would like _**to submit a project to the music map**_ in order to _**have it displayed in the user interface**_.
 
 #### Description
 The music map is created and curated by its users, and in order to do that, they need a way to submit a project to the music map.
 
 The user should be able to add a project (for example, an album) in a standard format with all necessary information needed to connect the people who have worked on that project to each other.
 
 #### Solution
 * [ ]  Form should have fields for each piece of necessary info.
   
   * [ ]  Forms must be able to add more entries to some fields
   * [ ]  Forms should add additional questions based on the answers to some fields (radio type selection)
 * [ ]  Optionally, the form should be able to fetch the necessary data from Discogs or another music metadata database.
 * [ ]  Upon pressing a "submit" button, the form should package the data into a transaction that can be sent to the blockchain.
 
 ### 👨‍💻 Deliverables
 #### Design
 * [ ]  Design project/release submission form
 * [ ]  Design Discogs fetch
 
 #### Smart Contract
 * [ ]  Package data from form into transaction
 
 #### Frontend
 * [ ]  Fields for:
   
   * [ ]  Data Source:
   * [ ]  Project Name
     
     * [ ]  (Optional) Alternate Project Names (Multiple)
   * [ ]  Project Release Date
   * [ ]  Project Re-Release? (Y/N)
   * [ ]  Master Project - Is this the canonical release of the project? (Y/N)
     
     * [ ]  (if no) Link to canonical project release
   * [ ]  Project Record Label
   * [ ]  Project Liner Notes
   * [ ]  Project Bio
   * [ ]  Project Artwork
   * [ ]  (Optional) Project Multimedia
   * [ ]  Project Groups (Multiple)
     
     * [ ]  + button to add more groups
   * [ ]  Project Artists (Multiple)
     
     * [ ]  + button to add more musicians
     * For Each:
     * [ ]  Name
     * [ ]  City
     * [ ]  Role
     * [ ]  Group Member? (Y/N)
       
       * [ ]  (If Y and multiple groups) Which Group? (Select from groups)
   * [ ]  Project Technicians (Multiple)
   * [ ]  + button to add more technicians
   * For Each:
   * [ ]  Name
   * [ ]  City
   * [ ]  Role
   * [ ]  Group Member? (Y/N)
     
     * [ ]  (If Y and multiple groups) Which Group? (Select from groups)
   * [ ]  Tracks (Multiple)
     
     * [ ]  + button to Add More Tracks
     * For Each:
     * [ ]  Track Number (Auto)
     * [ ]  Track Link (Spotify, Bandcamp, Apple Music, etc.)
     * [ ]  Track Name
     * [ ]  Track Songwriter - Lyrics (Auto-add group)
       
       * [ ]  + to add more
         
         * [ ]  - to delete
     * [ ]  Track Composer - Music (Auto-add group)
       
       * [ ]  + to add more
         
         * [ ]  - to delete
     * [ ]  Track Performers (auto-add group)
       
       * [ ]  + to add more
         
         * [ ]  - to delete
     * [ ]  Track Technicians (Multiple)
       
       * [ ]  + to add more
 

## Base Reward
**45.0000 USDT**

## Note
For technical discussion use the original issue. This issue is for tracking the bounty application and implementation progress.

**Comment by PomeloBounties** [comment]
Bounty fully [funded](https://bloks.io/transaction/f22db0d42597a65d29a2775e1ee5b916fcf82148b618b7538b8141c9e4f1239e) with **45.0000 USDT** reward!

Accepting applications [here](https://bounties.pomelo.io/14e2144db1bc)

**Comment by PomeloBounties** [comment]
Bounty application submitted by @nadiaalicante1 with a message:
 > giving feedbacks every news feed I read that means I'm active

Waiting for your approval @andrewrec

**Comment by PomeloBounties** [comment]
Bounty application submitted by @Dublin7 with a message:
 > N/A

Waiting for your approval @andrewrec

**Comment by PomeloBounties** [comment]
Bounty application submitted by @Adi12113 with a message:
 > N/A

Waiting for your approval @andrewrec

**Comment by nadiaalicante1** [comment]
It's nice activity

**Comment by PomeloBounties** [comment]
Bounty application submitted by @Daddie-b with a message:
 > We can do this form,

Waiting for your approval @andrewrec

**Comment by PomeloBounties** [comment]
Bounty application submitted by @InnaKoliasnikova with a message:
 > 1. Название проекта: Motodex
> 2. Oписание:
> Используя весь свой опыт в сфере блокчейна, моя команда создала уникальную игру. Простота выбора персонажа и интуитивно понятный игровой процесс. Незамысловатый сюжет в сочетании с драйвом скоростных гонок!

Waiting for your approval @andrewrec

**Comment by PomeloBounties** [comment]
Bounty application submitted by @tofan428 with a message:
 > N/A

Waiting for your approval @andrewrec

**Comment by PomeloBounties** [comment]
Bounty application submitted by @Darkmobstah with a message:
 > How?

Waiting for your approval @andrewrec

**Comment by PomeloBounties** [comment]
Bounty application submitted by @Ken2889 with a message:
 > Give

Waiting for your approval @andrewrec

**Comment by PomeloBounties** [comment]
Bounty application submitted by @Mywalleteosz with a message:
 > N/A

Waiting for your approval @andrewrec

**Comment by InnaKoliasnikova** [comment]
Please tell me what should we do? what are the next steps? Thank you!

ср, 31 июл. 2024 г. в 11:09, PomeloBounties ***@***.***>:

**Comment by PomeloBounties** [comment]
Bounty application submitted by @RajaAdeel1234 with a message:
 > Hallo RajaAdeel

Waiting for your approval @andrewrec

**Comment by InnaKoliasnikova** [comment]
Hello! I can't find this contact, check if you entered it correctly? Thank
you! @andrewrec <https://github.com/andrewrec>

вс, 25 авг. 2024 г. в 15:48, PomeloBounties ***@***.***>:

**Comment by PomeloBounties** [comment]
Bounty application submitted by @Tlorusso12 with a message:
 > Hi I’m motivated and driven with everything I do.  I will give you my best everyday 24/7….Ive been studying digital currencies for probably 5 years and I’ve learned a lot and I know I need to learn even more and I’m available to go when you say.

Waiting for your approval @andrewrec

**Comment by PomeloBounties** [comment]
Bounty closed by the funder

**Comment by PomeloBounties** [comment]
Bounty funds [withdrawn](https://bloks.io/transaction/106452c17a114bb4e332c93bcaa3b5b11d768bbcde7442f05f9769edc4689512) by the funder
